#!/bin/bash

# Docker
alias dc="docker-compose"
alias dcb="docker-compose -f docker-compose-build.yml"
alias dcd="docker-compose -f docker-compose-dev.yml"
alias dce="docker-compose -f docker-compose-experiment.yml"
alias dockerRmDiffs="sudo service docker stop; sudo rm -rf /var/lib/docker/aufs/diff; sudo service docker start"
alias dockerStopAll="docker stop \$(docker ps -a -q)";
alias dockerRmAll="docker rm \$(docker ps -a -q)";
alias dockerRmVolumes="docker volume rm \`docker volume ls -q -f dangling=true\`"
alias dockerRmDanglingImages="docker rmi \$(docker images -aq --filter dangling=true)"
alias dockerCleanUp="dockerStopAll; dockerRmAll; dockerRmVolumes; dockerRmDanglingImages; docker network prune; dockerRmDiffs"

# Git
alias gcob="git checkout -b"
alias gco="git checkout"
alias gcot="git checkout --theirs"
alias gom="git checkout master; git pull origin master"
alias gma="git rebase --abort";
alias gpo="branchName=\`git rev-parse --abbrev-ref HEAD\`; git push origin \$branchName";
alias grm="branchName=\`git rev-parse --abbrev-ref HEAD\`; gpo; gom; git checkout \$branchName; git rebase -i master";
alias gpu="branchName=\`git rev-parse --abbrev-ref HEAD\`; git pull origin \$branchName";
alias gst="git status"
alias gd="git diff"
alias gau="git add -u"
alias ga="git add"
alias gai="git add -i"
alias gc="git commit"
alias gss="git stash save"
alias gsp="git stash pop"
alias gsa="git stash apply"
alias gp="branchName=\`git rev-parse --abbrev-ref HEAD\`; git pull origin \$branchName;"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias gr="git reset ."
alias grh="git reset HEAD "
alias gruf="git clean -fd"
alias ghr="branchName=\`git rev-parse --abbrev-ref HEAD\`; git fetch origin; git reset --hard \$branchName"
alias glc='git log --format=%H -n1'
alias gro="git reset --hard HEAD~1"

# misc
alias reloadSource="source ~/.zshrc"
alias fd=fdfind
alias toClipBoard="xclip -i -selection clipboard"
alias ssh="ssh -v"
alias ws="cd ~/workspace"
alias listLargeFiles="sudo du -h / 2>/dev/null | grep '[0-9\.]\+G'"
alias ls="exa -alh --color=auto"
alias done="notify-send -i face-wink 'done'"
alias gem="vi -p \`gst | awk '/both modified:/ { print \$3 }'\`"
alias fdf="fd --type f"
alias fdd="fd --type d"
alias usKeyboardLayout="setxkbmap -layout us"
alias gbKeyboardLayout="setxkbmap -layout gb"

alias turnOffLaptopDisplay="xrandr --output eDP1 --off"
alias turnOnLaptopDisplay="xrandr --output eDP1 --mode 3840x2160 --rate 60.00"
alias turnOnHomeDisplay="xrandr --output DP3 --mode 3840x2160 --rate 30.00"
alias turnOnWorkDisplay="xrandr --output DP3 --mode 2048x1080 --rate 60.00 --dpi 117.50 --scale 2x2"
