#!/bin/bash
alias blueprintDb="docker exec -it atlas_postgres_1 psql --user blueprint development_blueprint"
alias toClipBoard="xclip -i -selection clipboard"
alias loginToDockerReg="aws --profile production ecr get-login --region eu-west-1"
alias ssh="ssh -v"
alias dc="docker-compose"
alias goToPrimitives="cd ~/workspace/infra/docker/primitives"
alias goToWorkspace="cd ~/workspace"
alias restartNetwork="sudo service network-manager stop; sudo rm -rf /var/lib/NetworkManager/NetworkManager.state; sudo service network-manager start"
alias dockerStopAll="docker stop \$(docker ps -a -q)";
alias dockerRmAll="docker rm \$(docker ps -a -q)";
