#!/bin/bash

eval `ssh-agent -s`

# power management
xfce4-power-manager &

# Handle external media
udiskie &

# Load wallpaper
feh --bg-scale /usr/share/backgrounds/warty-final-ubuntu.png &

# Load resources
xrdb -merge .Xresources

# Set up an icon tray
stalonetray &

# Fire up apps
xscreensaver -no-splash &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

#exec xmonad
